from fastapi import APIRouter, HTTPException, Path, status
from bd.mongo_client import Connection
from models.enterprise import Enterprise
from typing import List

router = APIRouter()

# Instantiate Connection objects globally for efficiency
enterprise_db = Connection(collection_name="Enterprise")
# Assuming you have a 'categories' collection for enterprise categories
category_db = Connection(collection_name="categories")

# Example response for Swagger UI - updated to match the Enterprise model
# The _id will be generated by MongoDB, so it's not part of the input example
# but will be part of the response model.
# For demo purposes, we can include it if representing a retrieved object.
demo_enterprise_response = {
    "id_empresa": "68674b8ef6585d5be64e81c3", # This would be generated
    "nombre_empresa": "Example Corp.",
    "categoria": "Restaurants",
    "informacion_empresa": "A company focused on software development.",
    "horario": "Monday to Friday from 8am to 5pm",
    "telefono": "+506 8888 8888",
    "correo_electronico": "info@example.com",
    "direccion": "123 Street, San José, Costa Rica",
    "tipo_cedula": "personal",
    "numero_cedula": "3007001010"
}

@router.post(
    "/REGISTER_ENTERPRISE",
    response_model=Enterprise,
    status_code=status.HTTP_201_CREATED,
    summary="Register a new enterprise",
    tags=["Enterprises"],
    response_description="The newly registered enterprise with its generated ID."
)
async def register_enterprise(enterprise: Enterprise):
    """
    Registers a new enterprise in the database.
    - Prevents registration if an enterprise with the same 'numero_cedula' already exists.
    - Returns the newly created enterprise document, including its MongoDB '_id' mapped to 'id_empresa'.
    """
    try:
        # 1. Check for duplicate enterprise by numero_cedula
        # existing_enterprise será un diccionario si se encuentra, o None si no.
        existing_enterprise = enterprise_db.find_one({"numero_cedula": enterprise.numero_cedula})
        if existing_enterprise: # Si el resultado NO es None, significa que encontramos un duplicado
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Ya existe una empresa registrada con este número de cédula."
            )

        # 2. Insert into DB
        enterprise_dict = enterprise.model_dump(by_alias=True, exclude_unset=True)
        enterprise_dict.pop("_id", None)
        enterprise_dict.pop("id_empresa", None)

        result_doc = enterprise_db.create_data(enterprise_dict)

        return Enterprise(**result_doc)

    except HTTPException as e:
        raise e
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ocurrió un error inesperado al registrar la empresa: {str(e)}"
        )

@router.get(
    "/ENTERPRISE_BY_ID/{id}",
    response_model=Enterprise,
    summary="Get enterprise by ID",
    tags=["Enterprises"],
    response_description="Details of the enterprise matching the provided ID."
)
def get_enterprise_by_id(id: str = Path(..., example="68674b8ef6585d5be64e81c3")):
    """
    Retrieve enterprise data by its MongoDB ObjectId.
    """
    try:
        data = enterprise_db.get_by_id(id)
        # Pydantic Enterprise model will automatically map '_id' to 'id_empresa'
        return Enterprise(**data)
    except HTTPException as e:
        raise e
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ocurrió un error inesperado al buscar la empresa por ID: {str(e)}"
        )

@router.get(
    "/ENTERPRISES_BY_CATEGORY/{category_name}",
    response_model=List[Enterprise],
    summary="Get enterprises by category",
    tags=["Enterprises"],
    response_description="A list of enterprises belonging to the specified category."
)
def get_enterprises_by_category(category_name: str = Path(..., example="Restaurants")):
    """
    Retrieve a list of enterprises belonging to a specific category.
    """
    try:
        # Check if the category exists in the categories collection
        existing_category = category_db.find_one({"name": category_name})
        if not existing_category:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"La categoría '{category_name}' no existe."
            )

        # Find enterprises by category name
        enterprises_data = enterprise_db.find_many({"categoria": category_name})

        if not enterprises_data:
            # If the category exists but no enterprises are found, return 404 with a specific message
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No se encontraron empresas en la categoría '{category_name}'."
            )

        # Map each document to the Enterprise Pydantic model
        return [Enterprise(**doc) for doc in enterprises_data]

    except HTTPException as e:
        raise e
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ocurrió un error inesperado al buscar empresas por categoría: {str(e)}"
        )

