# Success Messages
SUCCESS = "SUCCESS"
CREATED = "CREATED"

# Error Messages
BAD_REQUEST = "BAD_REQUEST"
UNAUTHORIZED = "UNAUTHORIZED"
NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

# User Messages
USER_CREATED = "USER_CREATED"
USER_FOUND = "USER_FOUND"
USER_UPDATED = "USER_UPDATED"
USER_DELETED = "USER_DELETED"
USER_NOT_FOUND = "USER_NOT_FOUND"

# Business Messages
BUSINESS_CREATED = "BUSINESS_CREATED"
BUSINESS_FOUND = "BUSINESS_FOUND"
BUSINESS_UPDATED = "BUSINESS_UPDATED"
BUSINESS_DELETED = "BUSINESS_DELETED"
BUSINESS_NOT_FOUND = "BUSINESS_NOT_FOUND"

# Appointment Messages
APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
APPOINTMENT_FOUND = "APPOINTMENT_FOUND"
APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
APPOINTMENT_NOT_FOUND = "APPOINTMENT_NOT_FOUND"